### ISSUE TITLE
Switching Region and Profile

### ISSUE THREAD

**Issue by agregory999** [oracle-samples/oci-vscode-toolkit#17]
If ~/.oci/config has multiple profiles, the extension doesn't seem to allow switching unless going into the settings and changing the "default profile name" to what is needed.  Changing either the region or profile from VS Code and refreshing the Resource Manager tree seems to load only the stacks from the default profile that was in the extension config.

**Comment by omkar07** [comment]
Thanks for reporting the issue @agregory999. We have fixed the above issue in the version 1.0.3. Please give it a try and let us know if you have any concerns.

**Comment by omkar07** [comment]
Closing this issue as this issue is fixed in the version 1.0.3. Please feel free to open in case of any concerns.

**Comment by omkar07** [comment]
Closing this issue as this issue is fixed in the version 1.0.3. Please feel free to open in case of any concerns.
